apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  workspaces:
    - description: |
        This workspace is shared among all the pipeline tasks to read/write common resources
      name: source
  tasks:
    - name: test
      timeout: 30m
      retries: 0
      taskRef:
        kind: ClusterTask
        name: go-build
      workspaces:
        - name: source
          workspace: source
      when: []
      params:
        - name: command
          value: echo ok
        - name: build-outputs-path
          value: []
  git:
    options:
      depth: 1
      retries: 3
      timeout: 10m
      preScript: git config --global http.version HTTP/1.1
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 200Mi
  runTemplate:
    spec:
      taskRunSpecs: []
